name: Daily Paper Digest

on:
  schedule:
    # Ejecuta todos los días a las 8:00 AM (hora UTC)
    # Para Argentina (UTC-3), las 8 AM son las 11:00 UTC
    - cron: '0 11 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub

jobs:
  run-digest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai requests
    
    - name: Run digest script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      run: |
        cd automations/digestio-scholar
        python DigestoDiarioScholar.py